# Generated by Django 2.2.5 on 2019-09-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0004_auto_20190924_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_desc1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_desc2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_desc3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_desc4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_sub_desc5',
            field=models.TextField(blank=True, default=''),
        ),
    ]
