# Generated by Django 2.2.5 on 2019-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0005_auto_20190924_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDevService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_title_desc', models.CharField(max_length=5000)),
            ],
        ),
    ]
