# Generated by Django 2.2.5 on 2019-10-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0006_indexdevservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdevservice',
            name='service_title_desc',
            field=models.TextField(),
        ),
    ]
