# Generated by Django 2.2.5 on 2019-10-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0007_auto_20191008_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_img', models.ImageField(upload_to='index_img/service')),
                ('service_url', models.CharField(max_length=20)),
                ('service_created_date', models.DateTimeField(auto_now_add=True)),
                ('service_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
