# Generated by Django 2.2.5 on 2019-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0009_indexadress'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_head', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=100)),
                ('project_name', models.CharField(max_length=50)),
                ('language_used1', models.CharField(max_length=30)),
                ('language_used2', models.CharField(max_length=30)),
                ('language_used3', models.CharField(max_length=30)),
                ('language_used4', models.CharField(max_length=30)),
                ('project_desc1', models.TextField()),
                ('project_created_date', models.DateTimeField(auto_now_add=True)),
                ('project_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
