# Generated by Django 2.2.5 on 2019-10-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0010_indexproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexproject',
            name='project_img',
            field=models.ImageField(default='', upload_to='project_img/'),
        ),
    ]
