# Generated by Django 2.2.5 on 2019-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0011_indexproject_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexproject',
            name='project_desc2',
            field=models.TextField(default=''),
        ),
    ]
