# Generated by Django 2.2.5 on 2019-10-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0012_indexproject_project_desc2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSpeaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_company_name', models.CharField(max_length=30)),
                ('client_comment', models.CharField(max_length=300)),
                ('client_img', models.ImageField(upload_to='client_img/')),
                ('client_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
