# Generated by Django 2.2.5 on 2019-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0013_clientspeaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_title', models.CharField(max_length=50)),
                ('why_desc', models.TextField()),
                ('why_created_date', models.DateTimeField(auto_now_add=True)),
                ('why_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
