# Generated by Django 2.2.5 on 2019-10-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0014_whycompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrerPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=100)),
                ('carrer_heading', models.CharField(max_length=100)),
                ('career_title1', models.CharField(max_length=100)),
                ('carrer_heading1', models.CharField(max_length=100)),
                ('carrer_desc', models.TextField()),
                ('career_title2', models.CharField(max_length=100)),
                ('carrer_heading2', models.CharField(max_length=100)),
                ('carrer_desc1', models.TextField()),
                ('carrer_img', models.ImageField(upload_to='carrer_img/')),
                ('carrer_img1', models.ImageField(upload_to='carrer_img/')),
                ('carrer_created_date', models.DateTimeField(auto_now_add=True)),
                ('carrer_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
