# Generated by Django 2.2.5 on 2019-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0015_carrerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology_language', models.CharField(max_length=100)),
                ('job_desc', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_qulification', models.CharField(max_length=100)),
                ('job_experience', models.CharField(max_length=200)),
                ('job_about1', models.CharField(blank=True, max_length=200)),
                ('job_about2', models.CharField(blank=True, max_length=200)),
                ('job_about3', models.CharField(blank=True, max_length=200)),
                ('job_about4', models.CharField(blank=True, max_length=200)),
                ('job_about5', models.CharField(blank=True, max_length=200)),
                ('job_about6', models.CharField(blank=True, max_length=200)),
                ('job_about7', models.CharField(blank=True, max_length=200)),
                ('job_about8', models.CharField(blank=True, max_length=200)),
                ('job_about9', models.CharField(blank=True, max_length=200)),
                ('job_about10', models.CharField(blank=True, max_length=200)),
                ('job_about11', models.CharField(blank=True, max_length=200)),
                ('job_about12', models.CharField(blank=True, max_length=200)),
                ('job_created_date', models.DateTimeField(auto_now_add=True)),
                ('job_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
