# Generated by Django 2.2.5 on 2019-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0016_jobopening'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=55)),
                ('team_designation', models.CharField(max_length=55)),
                ('team_image', models.ImageField(upload_to='team_img/')),
                ('team_created_date', models.DateTimeField(auto_now_add=True)),
                ('team_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
