# Generated by Django 2.2.5 on 2019-10-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0017_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_process', models.CharField(max_length=55)),
                ('dev_desc', models.TextField()),
                ('dev_image', models.ImageField(upload_to='dev_img/')),
                ('dev_created_date', models.DateTimeField(auto_now_add=True)),
                ('dev_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
