# Generated by Django 2.2.5 on 2019-11-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0019_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='support_contact_emailid',
            field=models.CharField(default='', max_length=51),
        ),
        migrations.AddField(
            model_name='support',
            name='support_contact_emailid1',
            field=models.CharField(default='', max_length=51),
        ),
        migrations.AddField(
            model_name='support',
            name='support_contact_skypeid',
            field=models.CharField(default='', max_length=51),
        ),
        migrations.AddField(
            model_name='support',
            name='support_contact_skypeid1',
            field=models.CharField(default='', max_length=51),
        ),
        migrations.AddField(
            model_name='support',
            name='support_contact_titledesc',
            field=models.CharField(default='', max_length=251),
        ),
    ]
