# Generated by Django 2.2.5 on 2019-11-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0020_auto_20191101_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Php_Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(max_length=250)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(max_length=250)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(max_length=250)),
                ('answer4', models.TextField()),
            ],
        ),
    ]
