# Generated by Django 2.2.5 on 2019-11-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0021_faq_php_dev'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ_Php_Dev',
            new_name='FaqPhpDev',
        ),
    ]
