# Generated by Django 2.2.5 on 2019-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0022_auto_20191109_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetStartPhp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('php_title', models.CharField(max_length=251)),
                ('php_desc', models.CharField(max_length=551)),
                ('php_img1', models.ImageField(upload_to='Php_ico_img/')),
                ('php_img_title1', models.CharField(max_length=151)),
                ('php_img2', models.ImageField(upload_to='Php_ico_img/')),
                ('php_img_title2', models.CharField(max_length=151)),
                ('php_img3', models.ImageField(upload_to='Php_ico_img/')),
                ('php_img_title3', models.CharField(max_length=151)),
                ('php_img4', models.ImageField(upload_to='Php_ico_img/')),
                ('php_img_title4', models.CharField(max_length=151)),
            ],
        ),
    ]
