# Generated by Django 2.2.5 on 2019-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0024_projectlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevProcessPhp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_title', models.CharField(max_length=51)),
                ('dev_img', models.ImageField(upload_to='PHP_img/')),
                ('dev_desc', models.TextField()),
                ('dev_img_screen', models.ImageField(upload_to='PHP_img/laptop_screen')),
            ],
        ),
    ]
