# Generated by Django 2.2.5 on 2019-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0025_devprocessphp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddValuePhp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_value_php_title', models.CharField(max_length=51)),
                ('add_value_php_img', models.ImageField(upload_to='PHP_img/add_value')),
                ('add_value_php_desc', models.TextField()),
            ],
        ),
    ]
