# Generated by Django 2.2.5 on 2019-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0026_addvaluephp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionExpertisePhp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_exper_php_title', models.CharField(max_length=51)),
                ('sol_exper_php_img', models.ImageField(upload_to='PHP_img/solution_expertise')),
            ],
        ),
    ]
