# Generated by Django 2.2.5 on 2019-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0027_solutionexpertisephp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevServiceDescPhp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_php_desc', models.CharField(max_length=51)),
            ],
        ),
        migrations.CreateModel(
            name='DevServicePhp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_php_title', models.CharField(max_length=51)),
                ('dev_servic_php_img', models.ImageField(upload_to='PHP_img/dev_service')),
            ],
        ),
    ]
