# Generated by Django 2.2.5 on 2019-11-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0028_devservicedescphp_devservicephp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devservicedescphp',
            name='dev_service_php_desc',
            field=models.CharField(max_length=551),
        ),
    ]
