# Generated by Django 2.2.5 on 2019-11-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0029_auto_20191110_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhpDevCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('php_dev_title', models.CharField(max_length=51)),
                ('php_dev_desc', models.TextField()),
                ('php_dev_img', models.ImageField(upload_to='PHP_img/php_dev_company')),
            ],
        ),
    ]
