# Generated by Django 2.2.5 on 2019-11-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0031_addvaluedjango_devprocessdjango_devservicedescdjango_devservicedjango_djangodevcompany_faqdjangodev_'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddValuePython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_value_python_title', models.CharField(max_length=51)),
                ('add_value_python_img', models.ImageField(upload_to='python_img/add_value')),
                ('add_value_python_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevProcessPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_python_title', models.CharField(max_length=51)),
                ('dev_python_img', models.ImageField(upload_to='python_img/')),
                ('dev_python_desc', models.TextField()),
                ('dev_python_img_screen', models.ImageField(upload_to='python_img/laptop_screen')),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceDescPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_python_desc', models.CharField(max_length=551)),
            ],
        ),
        migrations.CreateModel(
            name='DevServicePython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_python_title', models.CharField(max_length=51)),
                ('dev_servic_python_img', models.ImageField(upload_to='python_img/dev_service')),
            ],
        ),
        migrations.CreateModel(
            name='FaqPythonDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(max_length=250)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(max_length=250)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(max_length=250)),
                ('answer4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GetStartPython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_title', models.CharField(max_length=251)),
                ('python_desc', models.CharField(max_length=551)),
                ('python_img1', models.ImageField(upload_to='python_ico_img/')),
                ('python_img_title1', models.CharField(max_length=151)),
                ('python_img2', models.ImageField(upload_to='python_ico_img/')),
                ('python_img_title2', models.CharField(max_length=151)),
                ('python_img3', models.ImageField(upload_to='python_ico_img/')),
                ('python_img_title3', models.CharField(max_length=151)),
                ('python_img4', models.ImageField(upload_to='python_ico_img/')),
                ('python_img_title4', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='PythonDevCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_dev_title', models.CharField(max_length=51)),
                ('python_dev_desc', models.TextField()),
                ('python_dev_img', models.ImageField(upload_to='python_img/django_dev_company')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionExpertisePython',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_exper_python_title', models.CharField(max_length=51)),
                ('sol_exper_python_img', models.ImageField(upload_to='python_img/solution_expertise')),
            ],
        ),
    ]
