# Generated by Django 2.2.5 on 2019-11-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0032_addvaluepython_devprocesspython_devservicedescpython_devservicepython_faqpythondev_getstartpython_py'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddValueLaravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_value_laravel_title', models.CharField(max_length=51)),
                ('add_value_laravel_img', models.ImageField(upload_to='laravel_img/add_value')),
                ('add_value_laravel_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddValueWordpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_value_wordpress_title', models.CharField(max_length=51)),
                ('add_value_wordpress_img', models.ImageField(upload_to='wordpress_img/add_value')),
                ('add_value_wordpress_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevProcessLaravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_laravel_title', models.CharField(max_length=51)),
                ('dev_laravel_img', models.ImageField(upload_to='laravel_img/')),
                ('dev_laravel_desc', models.TextField()),
                ('dev_laravel_img_screen', models.ImageField(upload_to='laravel_img/laptop_screen')),
            ],
        ),
        migrations.CreateModel(
            name='DevProcessWordpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_wordpress_title', models.CharField(max_length=51)),
                ('dev_wordpress_img', models.ImageField(upload_to='wordpress_img/')),
                ('dev_wordpress_desc', models.TextField()),
                ('dev_wordpress_img_screen', models.ImageField(upload_to='laravel_img/laptop_screen')),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceDescLaravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_laravel_desc', models.CharField(max_length=551)),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceDescWordpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_wordpress_desc', models.CharField(max_length=551)),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceLaravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_laravel_title', models.CharField(max_length=51)),
                ('dev_servic_laravel_img', models.ImageField(upload_to='laravel_img/dev_service')),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceWordpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_wordpress_title', models.CharField(max_length=51)),
                ('dev_servic_wordpress_img', models.ImageField(upload_to='wordpress_img/dev_service')),
            ],
        ),
        migrations.CreateModel(
            name='FaqLaravelDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(max_length=250)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(max_length=250)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(max_length=250)),
                ('answer4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FaqWordpressDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(max_length=250)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(max_length=250)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(max_length=250)),
                ('answer4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GetStartLaravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laravel_title', models.CharField(max_length=251)),
                ('laravel_desc', models.CharField(max_length=551)),
                ('laravel_img1', models.ImageField(upload_to='laravel_ico_img/')),
                ('laravel_img_title1', models.CharField(max_length=151)),
                ('laravel_img2', models.ImageField(upload_to='laravel_ico_img/')),
                ('laravel_img_title2', models.CharField(max_length=151)),
                ('laravel_img3', models.ImageField(upload_to='laravel_ico_img/')),
                ('laravel_img_title3', models.CharField(max_length=151)),
                ('laravel_img4', models.ImageField(upload_to='laravel_ico_img/')),
                ('laravel_img_title4', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='GetStartWordpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordpress_title', models.CharField(max_length=251)),
                ('wordpress_desc', models.CharField(max_length=551)),
                ('wordpress_img1', models.ImageField(upload_to='wordpress_ico_img/')),
                ('wordpress_img_title1', models.CharField(max_length=151)),
                ('wordpress_img2', models.ImageField(upload_to='wordpress_ico_img/')),
                ('wordpress_img_title2', models.CharField(max_length=151)),
                ('wordpress_img3', models.ImageField(upload_to='wordpress_ico_img/')),
                ('wordpress_img_title3', models.CharField(max_length=151)),
                ('wordpress_img4', models.ImageField(upload_to='wordpress_ico_img/')),
                ('wordpress_img_title4', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='LaravelDevCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laravel_dev_title', models.CharField(max_length=51)),
                ('laravel_dev_desc', models.TextField()),
                ('laravel_dev_img', models.ImageField(upload_to='laravel_img/django_dev_company')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionExpertiseLaravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_exper_laravel_title', models.CharField(max_length=51)),
                ('sol_exper_laravel_img', models.ImageField(upload_to='laravel_img/solution_expertise')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionExpertiseWordpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_exper_wordpress_title', models.CharField(max_length=51)),
                ('sol_exper_wordpress_img', models.ImageField(upload_to='wordpress_img/solution_expertise')),
            ],
        ),
        migrations.CreateModel(
            name='WordpressDevCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordpress_dev_title', models.CharField(max_length=51)),
                ('wordpress_dev_desc', models.TextField()),
                ('wordpress_dev_img', models.ImageField(upload_to='wordpress_img/django_dev_company')),
            ],
        ),
    ]
