# Generated by Django 2.2.5 on 2019-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0034_addvalueiosapp_devprocessiosapp_devservicedesciosapp_devserviceiosapp_faqiosappdev_getstartiosapp_io'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddValueAndroidAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_value_android_title', models.CharField(max_length=51)),
                ('add_value_android_img', models.ImageField(upload_to='android_img/add_value')),
                ('add_value_android_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AndroidAPPDevCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_dev_title', models.CharField(max_length=51)),
                ('android_dev_desc', models.TextField()),
                ('android_dev_img', models.ImageField(upload_to='android_img/django_dev_company')),
            ],
        ),
        migrations.CreateModel(
            name='DevProcessAndroidAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_android_title', models.CharField(max_length=51)),
                ('dev_android_img', models.ImageField(upload_to='android_img/')),
                ('dev_android_desc', models.TextField()),
                ('dev_android_img_screen', models.ImageField(upload_to='android_img/laptop_screen')),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceAndroidAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_android_title', models.CharField(max_length=51)),
                ('dev_servic_android_img', models.ImageField(upload_to='android_img/dev_service')),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceDescAndroidAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_android_desc', models.CharField(max_length=551)),
            ],
        ),
        migrations.CreateModel(
            name='FaqAndroidAPPDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(max_length=250)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(max_length=250)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(max_length=250)),
                ('answer4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GetStartAndroidAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_title', models.CharField(max_length=251)),
                ('android_desc', models.CharField(max_length=551)),
                ('android_img1', models.ImageField(upload_to='android_ico_img/')),
                ('android_img_title1', models.CharField(max_length=151)),
                ('android_img2', models.ImageField(upload_to='android_ico_img/')),
                ('android_img_title2', models.CharField(max_length=151)),
                ('android_img3', models.ImageField(upload_to='android_ico_img/')),
                ('android_img_title3', models.CharField(max_length=151)),
                ('android_img4', models.ImageField(upload_to='android_ico_img/')),
                ('android_img_title4', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionExpertiseAndroidAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_exper_android_title', models.CharField(max_length=51)),
                ('sol_exper_android_img', models.ImageField(upload_to='android_img/solution_expertise')),
            ],
        ),
    ]
