# Generated by Django 2.2.5 on 2019-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0035_addvalueandroidapp_androidappdevcompany_devprocessandroidapp_devserviceandroidapp_devservicedescandr'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddValueDrupal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_value_drupal_title', models.CharField(max_length=51)),
                ('add_value_drupal_img', models.ImageField(upload_to='drupal_img/add_value')),
                ('add_value_drupal_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AddValueMagento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_value_magento_title', models.CharField(max_length=51)),
                ('add_value_magento_img', models.ImageField(upload_to='magento_img/add_value')),
                ('add_value_magento_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevProcessDrupal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_drupal_title', models.CharField(max_length=51)),
                ('dev_drupal_img', models.ImageField(upload_to='drupal_img/')),
                ('dev_drupal_desc', models.TextField()),
                ('dev_drupal_img_screen', models.ImageField(upload_to='drupal_img/laptop_screen')),
            ],
        ),
        migrations.CreateModel(
            name='DevProcessMagento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_magento_title', models.CharField(max_length=51)),
                ('dev_magento_img', models.ImageField(upload_to='magento_img/')),
                ('dev_magento_desc', models.TextField()),
                ('dev_magento_img_screen', models.ImageField(upload_to='magento_img/laptop_screen')),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceDescDrupal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_drupal_desc', models.CharField(max_length=551)),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceDescMagento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_magento_desc', models.CharField(max_length=551)),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceDrupal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_drupal_title', models.CharField(max_length=51)),
                ('dev_servic_drupal_img', models.ImageField(upload_to='drupal_img/dev_service')),
            ],
        ),
        migrations.CreateModel(
            name='DevServiceMagento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_service_magento_title', models.CharField(max_length=51)),
                ('dev_servic_magento_img', models.ImageField(upload_to='magento_img/dev_service')),
            ],
        ),
        migrations.CreateModel(
            name='DrupalDevCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drupal_dev_title', models.CharField(max_length=51)),
                ('drupal_dev_desc', models.TextField()),
                ('drupal_dev_img', models.ImageField(upload_to='drupal_img/django_dev_company')),
            ],
        ),
        migrations.CreateModel(
            name='FaqDrupalDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(max_length=250)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(max_length=250)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(max_length=250)),
                ('answer4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FaqMagentoDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
                ('question2', models.CharField(max_length=250)),
                ('answer2', models.TextField()),
                ('question3', models.CharField(max_length=250)),
                ('answer3', models.TextField()),
                ('question4', models.CharField(max_length=250)),
                ('answer4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GetStartDrupal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drupal_title', models.CharField(max_length=251)),
                ('drupal_desc', models.CharField(max_length=551)),
                ('drupal_img1', models.ImageField(upload_to='drupal_ico_img/')),
                ('drupal_img_title1', models.CharField(max_length=151)),
                ('drupal_img2', models.ImageField(upload_to='drupal_ico_img/')),
                ('drupal_img_title2', models.CharField(max_length=151)),
                ('drupal_img3', models.ImageField(upload_to='drupal_ico_img/')),
                ('drupal_img_title3', models.CharField(max_length=151)),
                ('drupal_img4', models.ImageField(upload_to='drupal_ico_img/')),
                ('drupal_img_title4', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='GetStartMagento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magento_title', models.CharField(max_length=251)),
                ('magento_desc', models.CharField(max_length=551)),
                ('magento_img1', models.ImageField(upload_to='magento_ico_img/')),
                ('magento_img_title1', models.CharField(max_length=151)),
                ('magento_img2', models.ImageField(upload_to='magento_ico_img/')),
                ('magento_img_title2', models.CharField(max_length=151)),
                ('magento_img3', models.ImageField(upload_to='magento_ico_img/')),
                ('magento_img_title3', models.CharField(max_length=151)),
                ('magento_img4', models.ImageField(upload_to='magento_ico_img/')),
                ('magento_img_title4', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='MagentoDevCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magento_dev_title', models.CharField(max_length=51)),
                ('magento_dev_desc', models.TextField()),
                ('magento_dev_img', models.ImageField(upload_to='magento_img/django_dev_company')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionExpertiseDrupal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_exper_drupal_title', models.CharField(max_length=51)),
                ('sol_exper_drupal_img', models.ImageField(upload_to='drupal_img/solution_expertise')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionExpertiseMagento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_exper_magento_title', models.CharField(max_length=51)),
                ('sol_exper_magento_img', models.ImageField(upload_to='magento_img/solution_expertise')),
            ],
        ),
    ]
