# Generated by Django 2.2.5 on 2019-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0036_addvaluedrupal_addvaluemagento_devprocessdrupal_devprocessmagento_devservicedescdrupal_devservicedes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_head', models.CharField(max_length=151)),
                ('application_title', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDesignUi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_ui_head', models.CharField(max_length=151)),
                ('application_ui_title', models.CharField(max_length=151)),
                ('application_ui_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurDesignBerief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_design_title', models.CharField(max_length=251)),
                ('our_design_desc', models.TextField()),
                ('dev_servic_drupal_img', models.ImageField(upload_to='our_design_img')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm_title', models.CharField(max_length=151)),
                ('sm_desc', models.TextField()),
                ('sm_img', models.ImageField(upload_to='our_design_img')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smg_img', models.ImageField(upload_to='our_design_img')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_heading', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionDesignBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_design_brand_img', models.ImageField(upload_to='our_design_img')),
                ('sol_design_brand_title', models.CharField(max_length=151)),
                ('sol_design_brand_heading', models.CharField(max_length=151)),
                ('sol_design_brand_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolutionDesignTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_span', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='solutionWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_web_title', models.CharField(max_length=151)),
                ('sol_web_desc', models.TextField()),
                ('sol_web_img', models.ImageField(upload_to='our_design_img')),
            ],
        ),
        migrations.CreateModel(
            name='SpanTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_title1', models.CharField(max_length=251)),
                ('span_sol_desc', models.TextField()),
                ('span_sol_img', models.ImageField(upload_to='our_design_img')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_title', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyToolImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_img', models.ImageField(upload_to='our_design_img/tool_img')),
            ],
        ),
        migrations.CreateModel(
            name='UiTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_title', models.CharField(max_length=251)),
            ],
        ),
    ]
