# Generated by Django 2.2.5 on 2019-12-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0039_gemtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemTitle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem_title_heading', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='GemTitle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem_title_span', models.CharField(max_length=151)),
            ],
        ),
    ]
