# Generated by Django 2.2.5 on 2019-12-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0040_gemtitle1_gemtitle2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemTitleDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gem_title_desc', models.TextField()),
                ('gem_title_img', models.ImageField(upload_to='gem_title/gem_title_img')),
            ],
        ),
    ]
