# Generated by Django 2.2.5 on 2019-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0044_gemselleradvantage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemBuyerAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_advantage_title', models.CharField(max_length=251)),
            ],
        ),
        migrations.CreateModel(
            name='GemBuyerAdvantageDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_title', models.CharField(max_length=51)),
                ('buyer_desc', models.CharField(max_length=251)),
            ],
        ),
    ]
