# Generated by Django 2.2.5 on 2019-12-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0046_dsctitle_dsctitle1_dsctitle2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscTitleDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_title_desc', models.TextField()),
                ('dsc_title_img', models.ImageField(upload_to='dsc_title/dsc_title_img')),
            ],
        ),
    ]
