# Generated by Django 2.2.5 on 2019-12-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0047_dsctitledesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscClass2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_class2_title', models.CharField(max_length=151)),
                ('dsc_class2_head1', models.CharField(max_length=151)),
                ('dsc_class2_desc1', models.TextField()),
                ('dsc_class2_head2', models.CharField(max_length=151)),
                ('dsc_class2_desc2', models.TextField()),
                ('dsc_class2_use_title', models.CharField(max_length=151)),
                ('dsc_class2_use_desc', models.TextField()),
            ],
        ),
    ]
