# Generated by Django 2.2.5 on 2019-12-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0048_dscclass2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscClass2Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_class2_use_title', models.CharField(max_length=251)),
            ],
        ),
    ]
