# Generated by Django 2.2.5 on 2019-12-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0049_dscclass2use'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscClass3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_class3_title', models.CharField(max_length=151)),
                ('dsc_class3_head1', models.CharField(max_length=151)),
                ('dsc_class3_desc1', models.TextField()),
                ('dsc_class3_head2', models.CharField(max_length=151)),
                ('dsc_class3_desc2', models.TextField()),
                ('dsc_class3_use_title', models.CharField(max_length=151)),
                ('dsc_class3_use_desc', models.TextField()),
            ],
        ),
    ]
