# Generated by Django 2.2.5 on 2019-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0051_auto_20191216_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='DscClass3Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_class3_use_title', models.CharField(max_length=251)),
            ],
        ),
    ]
