# Generated by Django 2.2.5 on 2019-12-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0052_dscclass3use'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_title', models.CharField(max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='BiddingTitle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_title_heading', models.CharField(max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='BiddingTitle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_title_span', models.CharField(max_length=151)),
            ],
        ),
        migrations.CreateModel(
            name='BiddingTitleDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_title_desc', models.TextField()),
                ('bidding_title_img', models.ImageField(upload_to='bidding_title/bidding_title_img')),
            ],
        ),
    ]
