# Generated by Django 2.2.5 on 2019-12-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0053_biddingtitle_biddingtitle1_biddingtitle2_biddingtitledesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_part_title', models.CharField(max_length=151)),
                ('bidding_part_title1', models.CharField(max_length=151)),
            ],
        ),
    ]
