# Generated by Django 2.2.5 on 2019-12-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0054_biddingparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingparticipation',
            name='bidding_part_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingparticipation',
            name='bidding_part_desc1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
