# Generated by Django 2.2.5 on 2019-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0055_auto_20191216_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidParticiaptionHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_part_head', models.CharField(max_length=151)),
            ],
        ),
    ]
