# Generated by Django 2.2.5 on 2019-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0057_gempackage_gempackagehead_packageheading_tenderpackage_tenderpackagehead_webpackage_webpackagehead'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('language_used1', models.CharField(max_length=30)),
                ('language_used2', models.CharField(max_length=30)),
                ('language_used3', models.CharField(blank=True, max_length=30)),
                ('language_used4', models.CharField(blank=True, max_length=30)),
                ('language_used5', models.CharField(blank=True, max_length=30)),
                ('project_desc1', models.TextField(blank=True)),
                ('project_img1', models.ImageField(upload_to='work_project_img/')),
                ('project_img2', models.ImageField(upload_to='work_project_img/')),
                ('project_img3', models.ImageField(blank=True, upload_to='work_project_img/')),
                ('project_img4', models.ImageField(blank=True, upload_to='work_project_img/')),
                ('project_created_date', models.DateTimeField(auto_now_add=True)),
                ('project_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='gempackage',
            name='gem_package_title_list2',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='gempackage',
            name='gem_package_title_list3',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='gempackage',
            name='gem_package_title_list4',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='gempackage',
            name='gem_package_title_list5',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='tenderpackage',
            name='tender_package_title_list2',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='tenderpackage',
            name='tender_package_title_list3',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='tenderpackage',
            name='tender_package_title_list4',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='tenderpackage',
            name='tender_package_title_list5',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='webpackage',
            name='web_package_title_list2',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='webpackage',
            name='web_package_title_list3',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='webpackage',
            name='web_package_title_list4',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='webpackage',
            name='web_package_title_list5',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
