# Generated by Django 2.2.5 on 2019-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0060_auto_20191229_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactusform',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
