# Generated by Django 2.2.5 on 2019-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0061_auto_20191229_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusform',
            name='email_id',
            field=models.CharField(max_length=101),
        ),
    ]
