# Generated by Django 2.2.5 on 2020-01-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0062_auto_20191229_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocialFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_class', models.CharField(max_length=21)),
                ('social_link', models.CharField(max_length=151)),
                ('social_icon', models.CharField(max_length=21)),
                ('social_title', models.CharField(max_length=31)),
            ],
        ),
    ]
