# Generated by Django 2.2.5 on 2020-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0063_footersocialfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientspeaks',
            name='client_img',
            field=models.ImageField(default='default.png', upload_to='client_img/'),
        ),
    ]
