# Generated by Django 2.2.5 on 2020-02-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0064_auto_20200202_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientspeaks',
            name='client_img',
            field=models.ImageField(default='static/img/blog/default.png', upload_to=''),
        ),
    ]
