# Generated by Django 2.2.5 on 2020-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0065_auto_20200202_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientspeaks',
            name='client_comment',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='clientspeaks',
            name='client_img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
