# Generated by Django 2.2.5 on 2020-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websblog', '0066_auto_20200202_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqIosDev1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=250)),
                ('answer1', models.TextField()),
            ],
        ),
    ]
